steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/gcb-sandbox', '.' ]
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/felixduvallet/gcb-sandbox']
images:
- 'gcr.io/$PROJECT_ID/gcb-sandbox'
