steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/felixduvallet/gcb-sandbox']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-t', 'gcr.io/$PROJECT_ID/gcb-sandbox',
          '--cache-from', 'gcr.io/$PROJECT_ID/gcb-sandbox:latest',
          '.' ]
- 'gcr.io/$PROJECT_ID/gcb-sandbox'
