steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-t', 'gcr.io/$PROJECT_ID/gcb-sandbox',
          '--cache-from', 'gcr.io/$PROJECT_ID/gcb-sandbox:latest',
          '.' ]
images:
- 'gcr.io/$PROJECT_ID/gcb-sandbox'
