# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

references:
  defaults: &defaults
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

  run_build_container: &run_build_container
      name: Run container
      command:
        docker build -t vehicle_builder .

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: *run_build_container
      - run:
          name: Run container
          command:
            docker run -itd --name speedy_trucker vehicle_builder
      - run:
          name: Build code
          command:
            docker exec speedy_trucker /bin/sh -c "bazel build --verbose_failures --noexperimental_ui //source/..."
      - run:
          name: Run tests
          command:
            docker exec speedy_trucker /bin/sh -c "bazel test --verbose_failures --noexperimental_ui //source/..."

  lint_bazel:
    <<:  *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: *run_build_container
      - run:
          name: Run container
          command:
            docker run -itd --name speedy_trucker vehicle_builder
      - run:
          name: Check bazel file
          command:
            docker exec speedy_trucker /bin/sh -c "bazel run //:build_beautifier_check_only"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint_bazel
