# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

references:
  defaults: &defaults
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo


  workspace_root: &workspace_root
    /tmp/workspace

  run_build_container: &run_build_container
      name: Run container
      command:
        docker build -t vehicle_builder .

  initialize: &initialize
    name: Initialize
    command:
      mkdir -p /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: *initialize
      - setup_remote_docker:
          docker_layer_caching: true
      - run: *run_build_container
      - run:
          name: Save docker image
          command:
            mkdir -p /tmp/workspace/docker-cache && docker save --output /tmp/workspace/docker-cache/vehicle_builder.tar vehicle_builder
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker-cache/vehicle_builder.tar
      - run:
          name: Run container
          command:
            docker run -itd --name speedy_trucker vehicle_builder
      - run:
          name: Build code
          command:
            docker exec speedy_trucker /bin/sh -c "bazel build --verbose_failures --noexperimental_ui //source/..."
      - run:
          name: Run tests
          command:
            docker exec speedy_trucker /bin/sh -c "bazel test --verbose_failures --noexperimental_ui //source/..."

  load_container:
    <<:  *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load container
          command:
            docker load -i /tmp/workspace/docker-cache/vehicle_builder.tar
      - run:
          name: Run container
          command:
            docker run -itd --name speedy_trucker vehicle_builder

  lint_bazel:
    <<:  *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build vehicle docker
          command:
            docker build -t vehicle_builder .
      - run:
          name: Run container
          command:
            docker run -itd --name speedy_trucker vehicle_builder
      - run:
          name: Check bazel file
          command:
            docker exec speedy_trucker /bin/sh -c "bazel run //:build_beautifier_check_only"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - load_container:
          requires:
            - build
      - lint_bazel
