# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  prepare:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build vehicle docker
          command:
            docker build -t vehicle_builder .
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - run:
          name: Run container
          command:
            docker run -itd --name speedy_trucker vehicle_builder
      - run:
          name: Build code
          command:
            docker exec speedy_trucker /bin/sh -c "bazel build --verbose_failures --noexperimental_ui //source/..."
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - run:
          name: Run container
          command:
            docker run -itd --name speedy_trucker vehicle_builder
      - run:
          name: Run tests
          command:
            docker exec speedy_trucker /bin/sh -c "bazel test --verbose_failures --noexperimental_ui //source/..."

workflows:
  version: 2
  build_and_test:
    jobs:
      - prepare
      - build
          requires:
            - prepare
      - test:
          requires:
            - build
